source("utils/libraries.R")
source("utils/refresh_loading.R")
source("server/load_data.R")
source("server/company_dic.R")
source("server/functions/intro_var_plot.R")
source("server/functions/var_quantile_regression.R")
source("server/functions/covar_quantile_regression.R")
source("server/functions/panel_regression.R")
source("server/functions/describtive_data.R")
source("server/functions/plots.R")
source("ui/ui.R")
source("server/server.R")

shinyApp(ui, server)
